name: Build Server
on:
  push:
    branches: [main]
    paths:
      - "apps/server/**"
env:
  IMAGE_NAME: acme-server-test
  IMAGE_TAG: ${{ github.sha }}
  CR_REGISTRY: crpuj7sj0saatki2q31i21
jobs:
  # Deploy to EKS
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build . --file apps/server/Dockerfile --tag $IMAGE_NAME
      - name: Push Image
        run: |
          IMAGE_ID=cr.yandex/$CR_REGISTRY/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
          docker tag $IMAGE_NAME $IMAGE_ID:latest
